// Code generated by ent, DO NOT EDIT.

package accountimportsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldBatchID, v))
}

// EncryptedJSON applies equality check predicate on the "encrypted_json" field. It's identical to EncryptedJSONEQ.
func EncryptedJSON(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldEncryptedJSON, v))
}

// ImportedAt applies equality check predicate on the "imported_at" field. It's identical to ImportedAtEQ.
func ImportedAt(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldImportedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLTE(FieldAccountID, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNotIn(FieldBatchID, vs...))
}

// BatchIDGT applies the GT predicate on the "batch_id" field.
func BatchIDGT(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGT(FieldBatchID, v))
}

// BatchIDGTE applies the GTE predicate on the "batch_id" field.
func BatchIDGTE(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGTE(FieldBatchID, v))
}

// BatchIDLT applies the LT predicate on the "batch_id" field.
func BatchIDLT(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLT(FieldBatchID, v))
}

// BatchIDLTE applies the LTE predicate on the "batch_id" field.
func BatchIDLTE(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLTE(FieldBatchID, v))
}

// BatchIDContains applies the Contains predicate on the "batch_id" field.
func BatchIDContains(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldContains(FieldBatchID, v))
}

// BatchIDHasPrefix applies the HasPrefix predicate on the "batch_id" field.
func BatchIDHasPrefix(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldHasPrefix(FieldBatchID, v))
}

// BatchIDHasSuffix applies the HasSuffix predicate on the "batch_id" field.
func BatchIDHasSuffix(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldHasSuffix(FieldBatchID, v))
}

// BatchIDEqualFold applies the EqualFold predicate on the "batch_id" field.
func BatchIDEqualFold(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEqualFold(FieldBatchID, v))
}

// BatchIDContainsFold applies the ContainsFold predicate on the "batch_id" field.
func BatchIDContainsFold(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldContainsFold(FieldBatchID, v))
}

// EncryptedJSONEQ applies the EQ predicate on the "encrypted_json" field.
func EncryptedJSONEQ(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldEncryptedJSON, v))
}

// EncryptedJSONNEQ applies the NEQ predicate on the "encrypted_json" field.
func EncryptedJSONNEQ(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNEQ(FieldEncryptedJSON, v))
}

// EncryptedJSONIn applies the In predicate on the "encrypted_json" field.
func EncryptedJSONIn(vs ...string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldIn(FieldEncryptedJSON, vs...))
}

// EncryptedJSONNotIn applies the NotIn predicate on the "encrypted_json" field.
func EncryptedJSONNotIn(vs ...string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNotIn(FieldEncryptedJSON, vs...))
}

// EncryptedJSONGT applies the GT predicate on the "encrypted_json" field.
func EncryptedJSONGT(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGT(FieldEncryptedJSON, v))
}

// EncryptedJSONGTE applies the GTE predicate on the "encrypted_json" field.
func EncryptedJSONGTE(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGTE(FieldEncryptedJSON, v))
}

// EncryptedJSONLT applies the LT predicate on the "encrypted_json" field.
func EncryptedJSONLT(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLT(FieldEncryptedJSON, v))
}

// EncryptedJSONLTE applies the LTE predicate on the "encrypted_json" field.
func EncryptedJSONLTE(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLTE(FieldEncryptedJSON, v))
}

// EncryptedJSONContains applies the Contains predicate on the "encrypted_json" field.
func EncryptedJSONContains(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldContains(FieldEncryptedJSON, v))
}

// EncryptedJSONHasPrefix applies the HasPrefix predicate on the "encrypted_json" field.
func EncryptedJSONHasPrefix(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldHasPrefix(FieldEncryptedJSON, v))
}

// EncryptedJSONHasSuffix applies the HasSuffix predicate on the "encrypted_json" field.
func EncryptedJSONHasSuffix(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldHasSuffix(FieldEncryptedJSON, v))
}

// EncryptedJSONEqualFold applies the EqualFold predicate on the "encrypted_json" field.
func EncryptedJSONEqualFold(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEqualFold(FieldEncryptedJSON, v))
}

// EncryptedJSONContainsFold applies the ContainsFold predicate on the "encrypted_json" field.
func EncryptedJSONContainsFold(v string) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldContainsFold(FieldEncryptedJSON, v))
}

// ImportedAtEQ applies the EQ predicate on the "imported_at" field.
func ImportedAtEQ(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldImportedAt, v))
}

// ImportedAtNEQ applies the NEQ predicate on the "imported_at" field.
func ImportedAtNEQ(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNEQ(FieldImportedAt, v))
}

// ImportedAtIn applies the In predicate on the "imported_at" field.
func ImportedAtIn(vs ...time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldIn(FieldImportedAt, vs...))
}

// ImportedAtNotIn applies the NotIn predicate on the "imported_at" field.
func ImportedAtNotIn(vs ...time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNotIn(FieldImportedAt, vs...))
}

// ImportedAtGT applies the GT predicate on the "imported_at" field.
func ImportedAtGT(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGT(FieldImportedAt, v))
}

// ImportedAtGTE applies the GTE predicate on the "imported_at" field.
func ImportedAtGTE(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGTE(FieldImportedAt, v))
}

// ImportedAtLT applies the LT predicate on the "imported_at" field.
func ImportedAtLT(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLT(FieldImportedAt, v))
}

// ImportedAtLTE applies the LTE predicate on the "imported_at" field.
func ImportedAtLTE(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLTE(FieldImportedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountImportSnapshot) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountImportSnapshot) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountImportSnapshot) predicate.AccountImportSnapshot {
	return predicate.AccountImportSnapshot(sql.NotPredicates(p))
}
