// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountimportsnapshot"
)

// AccountImportSnapshot is the model entity for the AccountImportSnapshot schema.
type AccountImportSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// BatchID holds the value of the "batch_id" field.
	BatchID string `json:"batch_id,omitempty"`
	// EncryptedJSON holds the value of the "encrypted_json" field.
	EncryptedJSON string `json:"encrypted_json,omitempty"`
	// ImportedAt holds the value of the "imported_at" field.
	ImportedAt time.Time `json:"imported_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountImportSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountimportsnapshot.FieldID, accountimportsnapshot.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case accountimportsnapshot.FieldBatchID, accountimportsnapshot.FieldEncryptedJSON:
			values[i] = new(sql.NullString)
		case accountimportsnapshot.FieldImportedAt, accountimportsnapshot.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountImportSnapshot fields.
func (_m *AccountImportSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountimportsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountimportsnapshot.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountimportsnapshot.FieldBatchID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.String
			}
		case accountimportsnapshot.FieldEncryptedJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_json", values[i])
			} else if value.Valid {
				_m.EncryptedJSON = value.String
			}
		case accountimportsnapshot.FieldImportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field imported_at", values[i])
			} else if value.Valid {
				_m.ImportedAt = value.Time
			}
		case accountimportsnapshot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountImportSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *AccountImportSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountImportSnapshot.
// Note that you need to call AccountImportSnapshot.Unwrap() before calling this method if this AccountImportSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountImportSnapshot) Update() *AccountImportSnapshotUpdateOne {
	return NewAccountImportSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountImportSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountImportSnapshot) Unwrap() *AccountImportSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountImportSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountImportSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("AccountImportSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("batch_id=")
	builder.WriteString(_m.BatchID)
	builder.WriteString(", ")
	builder.WriteString("encrypted_json=")
	builder.WriteString(_m.EncryptedJSON)
	builder.WriteString(", ")
	builder.WriteString("imported_at=")
	builder.WriteString(_m.ImportedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountImportSnapshots is a parsable slice of AccountImportSnapshot.
type AccountImportSnapshots []*AccountImportSnapshot
