// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountimportsnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountImportSnapshotDelete is the builder for deleting a AccountImportSnapshot entity.
type AccountImportSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *AccountImportSnapshotMutation
}

// Where appends a list predicates to the AccountImportSnapshotDelete builder.
func (_d *AccountImportSnapshotDelete) Where(ps ...predicate.AccountImportSnapshot) *AccountImportSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountImportSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountImportSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountImportSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountimportsnapshot.Table, sqlgraph.NewFieldSpec(accountimportsnapshot.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountImportSnapshotDeleteOne is the builder for deleting a single AccountImportSnapshot entity.
type AccountImportSnapshotDeleteOne struct {
	_d *AccountImportSnapshotDelete
}

// Where appends a list predicates to the AccountImportSnapshotDelete builder.
func (_d *AccountImportSnapshotDeleteOne) Where(ps ...predicate.AccountImportSnapshot) *AccountImportSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountImportSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountimportsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountImportSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
