// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountimportsnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountImportSnapshotUpdate is the builder for updating AccountImportSnapshot entities.
type AccountImportSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *AccountImportSnapshotMutation
}

// Where appends a list predicates to the AccountImportSnapshotUpdate builder.
func (_u *AccountImportSnapshotUpdate) Where(ps ...predicate.AccountImportSnapshot) *AccountImportSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountImportSnapshotUpdate) SetAccountID(v int64) *AccountImportSnapshotUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdate) SetNillableAccountID(v *int64) *AccountImportSnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountImportSnapshotUpdate) AddAccountID(v int64) *AccountImportSnapshotUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *AccountImportSnapshotUpdate) SetBatchID(v string) *AccountImportSnapshotUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdate) SetNillableBatchID(v *string) *AccountImportSnapshotUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetEncryptedJSON sets the "encrypted_json" field.
func (_u *AccountImportSnapshotUpdate) SetEncryptedJSON(v string) *AccountImportSnapshotUpdate {
	_u.mutation.SetEncryptedJSON(v)
	return _u
}

// SetNillableEncryptedJSON sets the "encrypted_json" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdate) SetNillableEncryptedJSON(v *string) *AccountImportSnapshotUpdate {
	if v != nil {
		_u.SetEncryptedJSON(*v)
	}
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *AccountImportSnapshotUpdate) SetImportedAt(v time.Time) *AccountImportSnapshotUpdate {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdate) SetNillableImportedAt(v *time.Time) *AccountImportSnapshotUpdate {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountImportSnapshotUpdate) SetUpdatedAt(v time.Time) *AccountImportSnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountImportSnapshotMutation object of the builder.
func (_u *AccountImportSnapshotUpdate) Mutation() *AccountImportSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountImportSnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountImportSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountImportSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountImportSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountImportSnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountimportsnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountImportSnapshotUpdate) check() error {
	if v, ok := _u.mutation.BatchID(); ok {
		if err := accountimportsnapshot.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "AccountImportSnapshot.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountImportSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountimportsnapshot.Table, accountimportsnapshot.Columns, sqlgraph.NewFieldSpec(accountimportsnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountimportsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountimportsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(accountimportsnapshot.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedJSON(); ok {
		_spec.SetField(accountimportsnapshot.FieldEncryptedJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(accountimportsnapshot.FieldImportedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountimportsnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountimportsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountImportSnapshotUpdateOne is the builder for updating a single AccountImportSnapshot entity.
type AccountImportSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountImportSnapshotMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountImportSnapshotUpdateOne) SetAccountID(v int64) *AccountImportSnapshotUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdateOne) SetNillableAccountID(v *int64) *AccountImportSnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountImportSnapshotUpdateOne) AddAccountID(v int64) *AccountImportSnapshotUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *AccountImportSnapshotUpdateOne) SetBatchID(v string) *AccountImportSnapshotUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdateOne) SetNillableBatchID(v *string) *AccountImportSnapshotUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetEncryptedJSON sets the "encrypted_json" field.
func (_u *AccountImportSnapshotUpdateOne) SetEncryptedJSON(v string) *AccountImportSnapshotUpdateOne {
	_u.mutation.SetEncryptedJSON(v)
	return _u
}

// SetNillableEncryptedJSON sets the "encrypted_json" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdateOne) SetNillableEncryptedJSON(v *string) *AccountImportSnapshotUpdateOne {
	if v != nil {
		_u.SetEncryptedJSON(*v)
	}
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *AccountImportSnapshotUpdateOne) SetImportedAt(v time.Time) *AccountImportSnapshotUpdateOne {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *AccountImportSnapshotUpdateOne) SetNillableImportedAt(v *time.Time) *AccountImportSnapshotUpdateOne {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountImportSnapshotUpdateOne) SetUpdatedAt(v time.Time) *AccountImportSnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountImportSnapshotMutation object of the builder.
func (_u *AccountImportSnapshotUpdateOne) Mutation() *AccountImportSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountImportSnapshotUpdate builder.
func (_u *AccountImportSnapshotUpdateOne) Where(ps ...predicate.AccountImportSnapshot) *AccountImportSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountImportSnapshotUpdateOne) Select(field string, fields ...string) *AccountImportSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountImportSnapshot entity.
func (_u *AccountImportSnapshotUpdateOne) Save(ctx context.Context) (*AccountImportSnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountImportSnapshotUpdateOne) SaveX(ctx context.Context) *AccountImportSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountImportSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountImportSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountImportSnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountimportsnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountImportSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.BatchID(); ok {
		if err := accountimportsnapshot.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "AccountImportSnapshot.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountImportSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *AccountImportSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountimportsnapshot.Table, accountimportsnapshot.Columns, sqlgraph.NewFieldSpec(accountimportsnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountImportSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountimportsnapshot.FieldID)
		for _, f := range fields {
			if !accountimportsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountimportsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountimportsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountimportsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(accountimportsnapshot.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedJSON(); ok {
		_spec.SetField(accountimportsnapshot.FieldEncryptedJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(accountimportsnapshot.FieldImportedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountimportsnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AccountImportSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountimportsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
