// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountimportsnapshot"
)

// AccountImportSnapshotCreate is the builder for creating a AccountImportSnapshot entity.
type AccountImportSnapshotCreate struct {
	config
	mutation *AccountImportSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountImportSnapshotCreate) SetAccountID(v int64) *AccountImportSnapshotCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetBatchID sets the "batch_id" field.
func (_c *AccountImportSnapshotCreate) SetBatchID(v string) *AccountImportSnapshotCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetEncryptedJSON sets the "encrypted_json" field.
func (_c *AccountImportSnapshotCreate) SetEncryptedJSON(v string) *AccountImportSnapshotCreate {
	_c.mutation.SetEncryptedJSON(v)
	return _c
}

// SetImportedAt sets the "imported_at" field.
func (_c *AccountImportSnapshotCreate) SetImportedAt(v time.Time) *AccountImportSnapshotCreate {
	_c.mutation.SetImportedAt(v)
	return _c
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_c *AccountImportSnapshotCreate) SetNillableImportedAt(v *time.Time) *AccountImportSnapshotCreate {
	if v != nil {
		_c.SetImportedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountImportSnapshotCreate) SetUpdatedAt(v time.Time) *AccountImportSnapshotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountImportSnapshotCreate) SetNillableUpdatedAt(v *time.Time) *AccountImportSnapshotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AccountImportSnapshotMutation object of the builder.
func (_c *AccountImportSnapshotCreate) Mutation() *AccountImportSnapshotMutation {
	return _c.mutation
}

// Save creates the AccountImportSnapshot in the database.
func (_c *AccountImportSnapshotCreate) Save(ctx context.Context) (*AccountImportSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountImportSnapshotCreate) SaveX(ctx context.Context) *AccountImportSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountImportSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountImportSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountImportSnapshotCreate) defaults() {
	if _, ok := _c.mutation.ImportedAt(); !ok {
		v := accountimportsnapshot.DefaultImportedAt()
		_c.mutation.SetImportedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountimportsnapshot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountImportSnapshotCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountImportSnapshot.account_id"`)}
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "AccountImportSnapshot.batch_id"`)}
	}
	if v, ok := _c.mutation.BatchID(); ok {
		if err := accountimportsnapshot.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "AccountImportSnapshot.batch_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedJSON(); !ok {
		return &ValidationError{Name: "encrypted_json", err: errors.New(`ent: missing required field "AccountImportSnapshot.encrypted_json"`)}
	}
	if _, ok := _c.mutation.ImportedAt(); !ok {
		return &ValidationError{Name: "imported_at", err: errors.New(`ent: missing required field "AccountImportSnapshot.imported_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountImportSnapshot.updated_at"`)}
	}
	return nil
}

func (_c *AccountImportSnapshotCreate) sqlSave(ctx context.Context) (*AccountImportSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountImportSnapshotCreate) createSpec() (*AccountImportSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountImportSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountimportsnapshot.Table, sqlgraph.NewFieldSpec(accountimportsnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountimportsnapshot.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(accountimportsnapshot.FieldBatchID, field.TypeString, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.EncryptedJSON(); ok {
		_spec.SetField(accountimportsnapshot.FieldEncryptedJSON, field.TypeString, value)
		_node.EncryptedJSON = value
	}
	if value, ok := _c.mutation.ImportedAt(); ok {
		_spec.SetField(accountimportsnapshot.FieldImportedAt, field.TypeTime, value)
		_node.ImportedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountimportsnapshot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountImportSnapshot.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountImportSnapshotUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountImportSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *AccountImportSnapshotUpsertOne {
	_c.conflict = opts
	return &AccountImportSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountImportSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountImportSnapshotCreate) OnConflictColumns(columns ...string) *AccountImportSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountImportSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// AccountImportSnapshotUpsertOne is the builder for "upsert"-ing
	//  one AccountImportSnapshot node.
	AccountImportSnapshotUpsertOne struct {
		create *AccountImportSnapshotCreate
	}

	// AccountImportSnapshotUpsert is the "OnConflict" setter.
	AccountImportSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountImportSnapshotUpsert) SetAccountID(v int64) *AccountImportSnapshotUpsert {
	u.Set(accountimportsnapshot.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsert) UpdateAccountID() *AccountImportSnapshotUpsert {
	u.SetExcluded(accountimportsnapshot.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountImportSnapshotUpsert) AddAccountID(v int64) *AccountImportSnapshotUpsert {
	u.Add(accountimportsnapshot.FieldAccountID, v)
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *AccountImportSnapshotUpsert) SetBatchID(v string) *AccountImportSnapshotUpsert {
	u.Set(accountimportsnapshot.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsert) UpdateBatchID() *AccountImportSnapshotUpsert {
	u.SetExcluded(accountimportsnapshot.FieldBatchID)
	return u
}

// SetEncryptedJSON sets the "encrypted_json" field.
func (u *AccountImportSnapshotUpsert) SetEncryptedJSON(v string) *AccountImportSnapshotUpsert {
	u.Set(accountimportsnapshot.FieldEncryptedJSON, v)
	return u
}

// UpdateEncryptedJSON sets the "encrypted_json" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsert) UpdateEncryptedJSON() *AccountImportSnapshotUpsert {
	u.SetExcluded(accountimportsnapshot.FieldEncryptedJSON)
	return u
}

// SetImportedAt sets the "imported_at" field.
func (u *AccountImportSnapshotUpsert) SetImportedAt(v time.Time) *AccountImportSnapshotUpsert {
	u.Set(accountimportsnapshot.FieldImportedAt, v)
	return u
}

// UpdateImportedAt sets the "imported_at" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsert) UpdateImportedAt() *AccountImportSnapshotUpsert {
	u.SetExcluded(accountimportsnapshot.FieldImportedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountImportSnapshotUpsert) SetUpdatedAt(v time.Time) *AccountImportSnapshotUpsert {
	u.Set(accountimportsnapshot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsert) UpdateUpdatedAt() *AccountImportSnapshotUpsert {
	u.SetExcluded(accountimportsnapshot.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountImportSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountImportSnapshotUpsertOne) UpdateNewValues() *AccountImportSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountImportSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountImportSnapshotUpsertOne) Ignore() *AccountImportSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountImportSnapshotUpsertOne) DoNothing() *AccountImportSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountImportSnapshotCreate.OnConflict
// documentation for more info.
func (u *AccountImportSnapshotUpsertOne) Update(set func(*AccountImportSnapshotUpsert)) *AccountImportSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountImportSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountImportSnapshotUpsertOne) SetAccountID(v int64) *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountImportSnapshotUpsertOne) AddAccountID(v int64) *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertOne) UpdateAccountID() *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *AccountImportSnapshotUpsertOne) SetBatchID(v string) *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertOne) UpdateBatchID() *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateBatchID()
	})
}

// SetEncryptedJSON sets the "encrypted_json" field.
func (u *AccountImportSnapshotUpsertOne) SetEncryptedJSON(v string) *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetEncryptedJSON(v)
	})
}

// UpdateEncryptedJSON sets the "encrypted_json" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertOne) UpdateEncryptedJSON() *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateEncryptedJSON()
	})
}

// SetImportedAt sets the "imported_at" field.
func (u *AccountImportSnapshotUpsertOne) SetImportedAt(v time.Time) *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetImportedAt(v)
	})
}

// UpdateImportedAt sets the "imported_at" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertOne) UpdateImportedAt() *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateImportedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountImportSnapshotUpsertOne) SetUpdatedAt(v time.Time) *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertOne) UpdateUpdatedAt() *AccountImportSnapshotUpsertOne {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountImportSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountImportSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountImportSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountImportSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountImportSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountImportSnapshotCreateBulk is the builder for creating many AccountImportSnapshot entities in bulk.
type AccountImportSnapshotCreateBulk struct {
	config
	err      error
	builders []*AccountImportSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountImportSnapshot entities in the database.
func (_c *AccountImportSnapshotCreateBulk) Save(ctx context.Context) ([]*AccountImportSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountImportSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountImportSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountImportSnapshotCreateBulk) SaveX(ctx context.Context) []*AccountImportSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountImportSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountImportSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountImportSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountImportSnapshotUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountImportSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountImportSnapshotUpsertBulk {
	_c.conflict = opts
	return &AccountImportSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountImportSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountImportSnapshotCreateBulk) OnConflictColumns(columns ...string) *AccountImportSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountImportSnapshotUpsertBulk{
		create: _c,
	}
}

// AccountImportSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountImportSnapshot nodes.
type AccountImportSnapshotUpsertBulk struct {
	create *AccountImportSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountImportSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountImportSnapshotUpsertBulk) UpdateNewValues() *AccountImportSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountImportSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountImportSnapshotUpsertBulk) Ignore() *AccountImportSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountImportSnapshotUpsertBulk) DoNothing() *AccountImportSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountImportSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *AccountImportSnapshotUpsertBulk) Update(set func(*AccountImportSnapshotUpsert)) *AccountImportSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountImportSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountImportSnapshotUpsertBulk) SetAccountID(v int64) *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountImportSnapshotUpsertBulk) AddAccountID(v int64) *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertBulk) UpdateAccountID() *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *AccountImportSnapshotUpsertBulk) SetBatchID(v string) *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertBulk) UpdateBatchID() *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateBatchID()
	})
}

// SetEncryptedJSON sets the "encrypted_json" field.
func (u *AccountImportSnapshotUpsertBulk) SetEncryptedJSON(v string) *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetEncryptedJSON(v)
	})
}

// UpdateEncryptedJSON sets the "encrypted_json" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertBulk) UpdateEncryptedJSON() *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateEncryptedJSON()
	})
}

// SetImportedAt sets the "imported_at" field.
func (u *AccountImportSnapshotUpsertBulk) SetImportedAt(v time.Time) *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetImportedAt(v)
	})
}

// UpdateImportedAt sets the "imported_at" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertBulk) UpdateImportedAt() *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateImportedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountImportSnapshotUpsertBulk) SetUpdatedAt(v time.Time) *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountImportSnapshotUpsertBulk) UpdateUpdatedAt() *AccountImportSnapshotUpsertBulk {
	return u.Update(func(s *AccountImportSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountImportSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountImportSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountImportSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountImportSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
