// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageprimarytask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImagePrimaryTaskUpdate is the builder for updating ImagePrimaryTask entities.
type ImagePrimaryTaskUpdate struct {
	config
	hooks    []Hook
	mutation *ImagePrimaryTaskMutation
}

// Where appends a list predicates to the ImagePrimaryTaskUpdate builder.
func (_u *ImagePrimaryTaskUpdate) Where(ps ...predicate.ImagePrimaryTask) *ImagePrimaryTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImagePrimaryTaskUpdate) SetUserID(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableUserID(v *int64) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImagePrimaryTaskUpdate) AddUserID(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ImagePrimaryTaskUpdate) SetAPIKeyID(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableAPIKeyID(v *int64) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ImagePrimaryTaskUpdate) AddAPIKeyID(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ImagePrimaryTaskUpdate) SetUsageLogID(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableUsageLogID(v *int64) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ImagePrimaryTaskUpdate) AddUsageLogID(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *ImagePrimaryTaskUpdate) ClearUsageLogID() *ImagePrimaryTaskUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ImagePrimaryTaskUpdate) SetProtocol(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableProtocol(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ImagePrimaryTaskUpdate) SetModel(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableModel(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *ImagePrimaryTaskUpdate) SetRequestHash(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableRequestHash(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *ImagePrimaryTaskUpdate) SetUpstreamTaskID(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableUpstreamTaskID(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *ImagePrimaryTaskUpdate) ClearUpstreamTaskID() *ImagePrimaryTaskUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImagePrimaryTaskUpdate) SetStatus(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableStatus(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFallbackReason sets the "fallback_reason" field.
func (_u *ImagePrimaryTaskUpdate) SetFallbackReason(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetFallbackReason(v)
	return _u
}

// SetNillableFallbackReason sets the "fallback_reason" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableFallbackReason(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetFallbackReason(*v)
	}
	return _u
}

// ClearFallbackReason clears the value of the "fallback_reason" field.
func (_u *ImagePrimaryTaskUpdate) ClearFallbackReason() *ImagePrimaryTaskUpdate {
	_u.mutation.ClearFallbackReason()
	return _u
}

// SetResultLocator sets the "result_locator" field.
func (_u *ImagePrimaryTaskUpdate) SetResultLocator(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetResultLocator(v)
	return _u
}

// SetNillableResultLocator sets the "result_locator" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableResultLocator(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetResultLocator(*v)
	}
	return _u
}

// ClearResultLocator clears the value of the "result_locator" field.
func (_u *ImagePrimaryTaskUpdate) ClearResultLocator() *ImagePrimaryTaskUpdate {
	_u.mutation.ClearResultLocator()
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *ImagePrimaryTaskUpdate) SetImageCount(v int) *ImagePrimaryTaskUpdate {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableImageCount(v *int) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *ImagePrimaryTaskUpdate) AddImageCount(v int) *ImagePrimaryTaskUpdate {
	_u.mutation.AddImageCount(v)
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *ImagePrimaryTaskUpdate) SetImageSize(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableImageSize(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// ClearImageSize clears the value of the "image_size" field.
func (_u *ImagePrimaryTaskUpdate) ClearImageSize() *ImagePrimaryTaskUpdate {
	_u.mutation.ClearImageSize()
	return _u
}

// SetPrimaryDurationMs sets the "primary_duration_ms" field.
func (_u *ImagePrimaryTaskUpdate) SetPrimaryDurationMs(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.ResetPrimaryDurationMs()
	_u.mutation.SetPrimaryDurationMs(v)
	return _u
}

// SetNillablePrimaryDurationMs sets the "primary_duration_ms" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillablePrimaryDurationMs(v *int64) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetPrimaryDurationMs(*v)
	}
	return _u
}

// AddPrimaryDurationMs adds value to the "primary_duration_ms" field.
func (_u *ImagePrimaryTaskUpdate) AddPrimaryDurationMs(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.AddPrimaryDurationMs(v)
	return _u
}

// SetFallbackDurationMs sets the "fallback_duration_ms" field.
func (_u *ImagePrimaryTaskUpdate) SetFallbackDurationMs(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.ResetFallbackDurationMs()
	_u.mutation.SetFallbackDurationMs(v)
	return _u
}

// SetNillableFallbackDurationMs sets the "fallback_duration_ms" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableFallbackDurationMs(v *int64) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetFallbackDurationMs(*v)
	}
	return _u
}

// AddFallbackDurationMs adds value to the "fallback_duration_ms" field.
func (_u *ImagePrimaryTaskUpdate) AddFallbackDurationMs(v int64) *ImagePrimaryTaskUpdate {
	_u.mutation.AddFallbackDurationMs(v)
	return _u
}

// SetSettlementState sets the "settlement_state" field.
func (_u *ImagePrimaryTaskUpdate) SetSettlementState(v string) *ImagePrimaryTaskUpdate {
	_u.mutation.SetSettlementState(v)
	return _u
}

// SetNillableSettlementState sets the "settlement_state" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableSettlementState(v *string) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetSettlementState(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImagePrimaryTaskUpdate) SetUpdatedAt(v time.Time) *ImagePrimaryTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ImagePrimaryTaskUpdate) SetExpiresAt(v time.Time) *ImagePrimaryTaskUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdate) SetNillableExpiresAt(v *time.Time) *ImagePrimaryTaskUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the ImagePrimaryTaskMutation object of the builder.
func (_u *ImagePrimaryTaskUpdate) Mutation() *ImagePrimaryTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImagePrimaryTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImagePrimaryTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImagePrimaryTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImagePrimaryTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImagePrimaryTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imageprimarytask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImagePrimaryTaskUpdate) check() error {
	if v, ok := _u.mutation.Protocol(); ok {
		if err := imageprimarytask.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imageprimarytask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := imageprimarytask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := imageprimarytask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imageprimarytask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FallbackReason(); ok {
		if err := imageprimarytask.FallbackReasonValidator(v); err != nil {
			return &ValidationError{Name: "fallback_reason", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.fallback_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSize(); ok {
		if err := imageprimarytask.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.image_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettlementState(); ok {
		if err := imageprimarytask.SettlementStateValidator(v); err != nil {
			return &ValidationError{Name: "settlement_state", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.settlement_state": %w`, err)}
		}
	}
	return nil
}

func (_u *ImagePrimaryTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageprimarytask.Table, imageprimarytask.Columns, sqlgraph.NewFieldSpec(imageprimarytask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imageprimarytask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imageprimarytask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(imageprimarytask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(imageprimarytask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(imageprimarytask.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(imageprimarytask.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(imageprimarytask.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(imageprimarytask.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imageprimarytask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(imageprimarytask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(imageprimarytask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(imageprimarytask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imageprimarytask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FallbackReason(); ok {
		_spec.SetField(imageprimarytask.FieldFallbackReason, field.TypeString, value)
	}
	if _u.mutation.FallbackReasonCleared() {
		_spec.ClearField(imageprimarytask.FieldFallbackReason, field.TypeString)
	}
	if value, ok := _u.mutation.ResultLocator(); ok {
		_spec.SetField(imageprimarytask.FieldResultLocator, field.TypeString, value)
	}
	if _u.mutation.ResultLocatorCleared() {
		_spec.ClearField(imageprimarytask.FieldResultLocator, field.TypeString)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(imageprimarytask.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(imageprimarytask.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(imageprimarytask.FieldImageSize, field.TypeString, value)
	}
	if _u.mutation.ImageSizeCleared() {
		_spec.ClearField(imageprimarytask.FieldImageSize, field.TypeString)
	}
	if value, ok := _u.mutation.PrimaryDurationMs(); ok {
		_spec.SetField(imageprimarytask.FieldPrimaryDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrimaryDurationMs(); ok {
		_spec.AddField(imageprimarytask.FieldPrimaryDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FallbackDurationMs(); ok {
		_spec.SetField(imageprimarytask.FieldFallbackDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackDurationMs(); ok {
		_spec.AddField(imageprimarytask.FieldFallbackDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SettlementState(); ok {
		_spec.SetField(imageprimarytask.FieldSettlementState, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageprimarytask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(imageprimarytask.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageprimarytask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImagePrimaryTaskUpdateOne is the builder for updating a single ImagePrimaryTask entity.
type ImagePrimaryTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImagePrimaryTaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *ImagePrimaryTaskUpdateOne) SetUserID(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableUserID(v *int64) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImagePrimaryTaskUpdateOne) AddUserID(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ImagePrimaryTaskUpdateOne) SetAPIKeyID(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableAPIKeyID(v *int64) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ImagePrimaryTaskUpdateOne) AddAPIKeyID(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ImagePrimaryTaskUpdateOne) SetUsageLogID(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableUsageLogID(v *int64) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ImagePrimaryTaskUpdateOne) AddUsageLogID(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *ImagePrimaryTaskUpdateOne) ClearUsageLogID() *ImagePrimaryTaskUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ImagePrimaryTaskUpdateOne) SetProtocol(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableProtocol(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ImagePrimaryTaskUpdateOne) SetModel(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableModel(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *ImagePrimaryTaskUpdateOne) SetRequestHash(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableRequestHash(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *ImagePrimaryTaskUpdateOne) SetUpstreamTaskID(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *ImagePrimaryTaskUpdateOne) ClearUpstreamTaskID() *ImagePrimaryTaskUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImagePrimaryTaskUpdateOne) SetStatus(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableStatus(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFallbackReason sets the "fallback_reason" field.
func (_u *ImagePrimaryTaskUpdateOne) SetFallbackReason(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetFallbackReason(v)
	return _u
}

// SetNillableFallbackReason sets the "fallback_reason" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableFallbackReason(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetFallbackReason(*v)
	}
	return _u
}

// ClearFallbackReason clears the value of the "fallback_reason" field.
func (_u *ImagePrimaryTaskUpdateOne) ClearFallbackReason() *ImagePrimaryTaskUpdateOne {
	_u.mutation.ClearFallbackReason()
	return _u
}

// SetResultLocator sets the "result_locator" field.
func (_u *ImagePrimaryTaskUpdateOne) SetResultLocator(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetResultLocator(v)
	return _u
}

// SetNillableResultLocator sets the "result_locator" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableResultLocator(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetResultLocator(*v)
	}
	return _u
}

// ClearResultLocator clears the value of the "result_locator" field.
func (_u *ImagePrimaryTaskUpdateOne) ClearResultLocator() *ImagePrimaryTaskUpdateOne {
	_u.mutation.ClearResultLocator()
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *ImagePrimaryTaskUpdateOne) SetImageCount(v int) *ImagePrimaryTaskUpdateOne {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableImageCount(v *int) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *ImagePrimaryTaskUpdateOne) AddImageCount(v int) *ImagePrimaryTaskUpdateOne {
	_u.mutation.AddImageCount(v)
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *ImagePrimaryTaskUpdateOne) SetImageSize(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableImageSize(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// ClearImageSize clears the value of the "image_size" field.
func (_u *ImagePrimaryTaskUpdateOne) ClearImageSize() *ImagePrimaryTaskUpdateOne {
	_u.mutation.ClearImageSize()
	return _u
}

// SetPrimaryDurationMs sets the "primary_duration_ms" field.
func (_u *ImagePrimaryTaskUpdateOne) SetPrimaryDurationMs(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.ResetPrimaryDurationMs()
	_u.mutation.SetPrimaryDurationMs(v)
	return _u
}

// SetNillablePrimaryDurationMs sets the "primary_duration_ms" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillablePrimaryDurationMs(v *int64) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetPrimaryDurationMs(*v)
	}
	return _u
}

// AddPrimaryDurationMs adds value to the "primary_duration_ms" field.
func (_u *ImagePrimaryTaskUpdateOne) AddPrimaryDurationMs(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.AddPrimaryDurationMs(v)
	return _u
}

// SetFallbackDurationMs sets the "fallback_duration_ms" field.
func (_u *ImagePrimaryTaskUpdateOne) SetFallbackDurationMs(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.ResetFallbackDurationMs()
	_u.mutation.SetFallbackDurationMs(v)
	return _u
}

// SetNillableFallbackDurationMs sets the "fallback_duration_ms" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableFallbackDurationMs(v *int64) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetFallbackDurationMs(*v)
	}
	return _u
}

// AddFallbackDurationMs adds value to the "fallback_duration_ms" field.
func (_u *ImagePrimaryTaskUpdateOne) AddFallbackDurationMs(v int64) *ImagePrimaryTaskUpdateOne {
	_u.mutation.AddFallbackDurationMs(v)
	return _u
}

// SetSettlementState sets the "settlement_state" field.
func (_u *ImagePrimaryTaskUpdateOne) SetSettlementState(v string) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetSettlementState(v)
	return _u
}

// SetNillableSettlementState sets the "settlement_state" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableSettlementState(v *string) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetSettlementState(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImagePrimaryTaskUpdateOne) SetUpdatedAt(v time.Time) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ImagePrimaryTaskUpdateOne) SetExpiresAt(v time.Time) *ImagePrimaryTaskUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ImagePrimaryTaskUpdateOne) SetNillableExpiresAt(v *time.Time) *ImagePrimaryTaskUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the ImagePrimaryTaskMutation object of the builder.
func (_u *ImagePrimaryTaskUpdateOne) Mutation() *ImagePrimaryTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImagePrimaryTaskUpdate builder.
func (_u *ImagePrimaryTaskUpdateOne) Where(ps ...predicate.ImagePrimaryTask) *ImagePrimaryTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImagePrimaryTaskUpdateOne) Select(field string, fields ...string) *ImagePrimaryTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImagePrimaryTask entity.
func (_u *ImagePrimaryTaskUpdateOne) Save(ctx context.Context) (*ImagePrimaryTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImagePrimaryTaskUpdateOne) SaveX(ctx context.Context) *ImagePrimaryTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImagePrimaryTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImagePrimaryTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImagePrimaryTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imageprimarytask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImagePrimaryTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Protocol(); ok {
		if err := imageprimarytask.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imageprimarytask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := imageprimarytask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := imageprimarytask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imageprimarytask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FallbackReason(); ok {
		if err := imageprimarytask.FallbackReasonValidator(v); err != nil {
			return &ValidationError{Name: "fallback_reason", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.fallback_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSize(); ok {
		if err := imageprimarytask.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.image_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettlementState(); ok {
		if err := imageprimarytask.SettlementStateValidator(v); err != nil {
			return &ValidationError{Name: "settlement_state", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.settlement_state": %w`, err)}
		}
	}
	return nil
}

func (_u *ImagePrimaryTaskUpdateOne) sqlSave(ctx context.Context) (_node *ImagePrimaryTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageprimarytask.Table, imageprimarytask.Columns, sqlgraph.NewFieldSpec(imageprimarytask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImagePrimaryTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageprimarytask.FieldID)
		for _, f := range fields {
			if !imageprimarytask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageprimarytask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imageprimarytask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imageprimarytask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(imageprimarytask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(imageprimarytask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(imageprimarytask.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(imageprimarytask.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(imageprimarytask.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(imageprimarytask.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imageprimarytask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(imageprimarytask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(imageprimarytask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(imageprimarytask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imageprimarytask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FallbackReason(); ok {
		_spec.SetField(imageprimarytask.FieldFallbackReason, field.TypeString, value)
	}
	if _u.mutation.FallbackReasonCleared() {
		_spec.ClearField(imageprimarytask.FieldFallbackReason, field.TypeString)
	}
	if value, ok := _u.mutation.ResultLocator(); ok {
		_spec.SetField(imageprimarytask.FieldResultLocator, field.TypeString, value)
	}
	if _u.mutation.ResultLocatorCleared() {
		_spec.ClearField(imageprimarytask.FieldResultLocator, field.TypeString)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(imageprimarytask.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(imageprimarytask.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(imageprimarytask.FieldImageSize, field.TypeString, value)
	}
	if _u.mutation.ImageSizeCleared() {
		_spec.ClearField(imageprimarytask.FieldImageSize, field.TypeString)
	}
	if value, ok := _u.mutation.PrimaryDurationMs(); ok {
		_spec.SetField(imageprimarytask.FieldPrimaryDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrimaryDurationMs(); ok {
		_spec.AddField(imageprimarytask.FieldPrimaryDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FallbackDurationMs(); ok {
		_spec.SetField(imageprimarytask.FieldFallbackDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackDurationMs(); ok {
		_spec.AddField(imageprimarytask.FieldFallbackDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SettlementState(); ok {
		_spec.SetField(imageprimarytask.FieldSettlementState, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageprimarytask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(imageprimarytask.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &ImagePrimaryTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageprimarytask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
