// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageprimarytask"
)

// ImagePrimaryTaskCreate is the builder for creating a ImagePrimaryTask entity.
type ImagePrimaryTaskCreate struct {
	config
	mutation *ImagePrimaryTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPublicID sets the "public_id" field.
func (_c *ImagePrimaryTaskCreate) SetPublicID(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImagePrimaryTaskCreate) SetUserID(v int64) *ImagePrimaryTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ImagePrimaryTaskCreate) SetAPIKeyID(v int64) *ImagePrimaryTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *ImagePrimaryTaskCreate) SetUsageLogID(v int64) *ImagePrimaryTaskCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableUsageLogID(v *int64) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *ImagePrimaryTaskCreate) SetProtocol(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *ImagePrimaryTaskCreate) SetModel(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *ImagePrimaryTaskCreate) SetRequestHash(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *ImagePrimaryTaskCreate) SetUpstreamTaskID(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableUpstreamTaskID(v *string) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetUpstreamTaskID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImagePrimaryTaskCreate) SetStatus(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableStatus(v *string) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFallbackReason sets the "fallback_reason" field.
func (_c *ImagePrimaryTaskCreate) SetFallbackReason(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetFallbackReason(v)
	return _c
}

// SetNillableFallbackReason sets the "fallback_reason" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableFallbackReason(v *string) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetFallbackReason(*v)
	}
	return _c
}

// SetResultLocator sets the "result_locator" field.
func (_c *ImagePrimaryTaskCreate) SetResultLocator(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetResultLocator(v)
	return _c
}

// SetNillableResultLocator sets the "result_locator" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableResultLocator(v *string) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetResultLocator(*v)
	}
	return _c
}

// SetImageCount sets the "image_count" field.
func (_c *ImagePrimaryTaskCreate) SetImageCount(v int) *ImagePrimaryTaskCreate {
	_c.mutation.SetImageCount(v)
	return _c
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableImageCount(v *int) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetImageCount(*v)
	}
	return _c
}

// SetImageSize sets the "image_size" field.
func (_c *ImagePrimaryTaskCreate) SetImageSize(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetImageSize(v)
	return _c
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableImageSize(v *string) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetImageSize(*v)
	}
	return _c
}

// SetPrimaryDurationMs sets the "primary_duration_ms" field.
func (_c *ImagePrimaryTaskCreate) SetPrimaryDurationMs(v int64) *ImagePrimaryTaskCreate {
	_c.mutation.SetPrimaryDurationMs(v)
	return _c
}

// SetNillablePrimaryDurationMs sets the "primary_duration_ms" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillablePrimaryDurationMs(v *int64) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetPrimaryDurationMs(*v)
	}
	return _c
}

// SetFallbackDurationMs sets the "fallback_duration_ms" field.
func (_c *ImagePrimaryTaskCreate) SetFallbackDurationMs(v int64) *ImagePrimaryTaskCreate {
	_c.mutation.SetFallbackDurationMs(v)
	return _c
}

// SetNillableFallbackDurationMs sets the "fallback_duration_ms" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableFallbackDurationMs(v *int64) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetFallbackDurationMs(*v)
	}
	return _c
}

// SetSettlementState sets the "settlement_state" field.
func (_c *ImagePrimaryTaskCreate) SetSettlementState(v string) *ImagePrimaryTaskCreate {
	_c.mutation.SetSettlementState(v)
	return _c
}

// SetNillableSettlementState sets the "settlement_state" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableSettlementState(v *string) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetSettlementState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImagePrimaryTaskCreate) SetCreatedAt(v time.Time) *ImagePrimaryTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableCreatedAt(v *time.Time) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImagePrimaryTaskCreate) SetUpdatedAt(v time.Time) *ImagePrimaryTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImagePrimaryTaskCreate) SetNillableUpdatedAt(v *time.Time) *ImagePrimaryTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ImagePrimaryTaskCreate) SetExpiresAt(v time.Time) *ImagePrimaryTaskCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the ImagePrimaryTaskMutation object of the builder.
func (_c *ImagePrimaryTaskCreate) Mutation() *ImagePrimaryTaskMutation {
	return _c.mutation
}

// Save creates the ImagePrimaryTask in the database.
func (_c *ImagePrimaryTaskCreate) Save(ctx context.Context) (*ImagePrimaryTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImagePrimaryTaskCreate) SaveX(ctx context.Context) *ImagePrimaryTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImagePrimaryTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImagePrimaryTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImagePrimaryTaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := imageprimarytask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		v := imageprimarytask.DefaultImageCount
		_c.mutation.SetImageCount(v)
	}
	if _, ok := _c.mutation.PrimaryDurationMs(); !ok {
		v := imageprimarytask.DefaultPrimaryDurationMs
		_c.mutation.SetPrimaryDurationMs(v)
	}
	if _, ok := _c.mutation.FallbackDurationMs(); !ok {
		v := imageprimarytask.DefaultFallbackDurationMs
		_c.mutation.SetFallbackDurationMs(v)
	}
	if _, ok := _c.mutation.SettlementState(); !ok {
		v := imageprimarytask.DefaultSettlementState
		_c.mutation.SetSettlementState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imageprimarytask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imageprimarytask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImagePrimaryTaskCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "ImagePrimaryTask.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := imageprimarytask.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImagePrimaryTask.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ImagePrimaryTask.api_key_id"`)}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "ImagePrimaryTask.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := imageprimarytask.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ImagePrimaryTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := imageprimarytask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "ImagePrimaryTask.request_hash"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := imageprimarytask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := imageprimarytask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.upstream_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImagePrimaryTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imageprimarytask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FallbackReason(); ok {
		if err := imageprimarytask.FallbackReasonValidator(v); err != nil {
			return &ValidationError{Name: "fallback_reason", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.fallback_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		return &ValidationError{Name: "image_count", err: errors.New(`ent: missing required field "ImagePrimaryTask.image_count"`)}
	}
	if v, ok := _c.mutation.ImageSize(); ok {
		if err := imageprimarytask.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.image_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrimaryDurationMs(); !ok {
		return &ValidationError{Name: "primary_duration_ms", err: errors.New(`ent: missing required field "ImagePrimaryTask.primary_duration_ms"`)}
	}
	if _, ok := _c.mutation.FallbackDurationMs(); !ok {
		return &ValidationError{Name: "fallback_duration_ms", err: errors.New(`ent: missing required field "ImagePrimaryTask.fallback_duration_ms"`)}
	}
	if _, ok := _c.mutation.SettlementState(); !ok {
		return &ValidationError{Name: "settlement_state", err: errors.New(`ent: missing required field "ImagePrimaryTask.settlement_state"`)}
	}
	if v, ok := _c.mutation.SettlementState(); ok {
		if err := imageprimarytask.SettlementStateValidator(v); err != nil {
			return &ValidationError{Name: "settlement_state", err: fmt.Errorf(`ent: validator failed for field "ImagePrimaryTask.settlement_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImagePrimaryTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImagePrimaryTask.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ImagePrimaryTask.expires_at"`)}
	}
	return nil
}

func (_c *ImagePrimaryTaskCreate) sqlSave(ctx context.Context) (*ImagePrimaryTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImagePrimaryTaskCreate) createSpec() (*ImagePrimaryTask, *sqlgraph.CreateSpec) {
	var (
		_node = &ImagePrimaryTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imageprimarytask.Table, sqlgraph.NewFieldSpec(imageprimarytask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(imageprimarytask.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imageprimarytask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(imageprimarytask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(imageprimarytask.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(imageprimarytask.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(imageprimarytask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(imageprimarytask.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(imageprimarytask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imageprimarytask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FallbackReason(); ok {
		_spec.SetField(imageprimarytask.FieldFallbackReason, field.TypeString, value)
		_node.FallbackReason = &value
	}
	if value, ok := _c.mutation.ResultLocator(); ok {
		_spec.SetField(imageprimarytask.FieldResultLocator, field.TypeString, value)
		_node.ResultLocator = &value
	}
	if value, ok := _c.mutation.ImageCount(); ok {
		_spec.SetField(imageprimarytask.FieldImageCount, field.TypeInt, value)
		_node.ImageCount = value
	}
	if value, ok := _c.mutation.ImageSize(); ok {
		_spec.SetField(imageprimarytask.FieldImageSize, field.TypeString, value)
		_node.ImageSize = &value
	}
	if value, ok := _c.mutation.PrimaryDurationMs(); ok {
		_spec.SetField(imageprimarytask.FieldPrimaryDurationMs, field.TypeInt64, value)
		_node.PrimaryDurationMs = value
	}
	if value, ok := _c.mutation.FallbackDurationMs(); ok {
		_spec.SetField(imageprimarytask.FieldFallbackDurationMs, field.TypeInt64, value)
		_node.FallbackDurationMs = value
	}
	if value, ok := _c.mutation.SettlementState(); ok {
		_spec.SetField(imageprimarytask.FieldSettlementState, field.TypeString, value)
		_node.SettlementState = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imageprimarytask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imageprimarytask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(imageprimarytask.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImagePrimaryTask.Create().
//		SetPublicID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImagePrimaryTaskUpsert) {
//			SetPublicID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImagePrimaryTaskCreate) OnConflict(opts ...sql.ConflictOption) *ImagePrimaryTaskUpsertOne {
	_c.conflict = opts
	return &ImagePrimaryTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImagePrimaryTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImagePrimaryTaskCreate) OnConflictColumns(columns ...string) *ImagePrimaryTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImagePrimaryTaskUpsertOne{
		create: _c,
	}
}

type (
	// ImagePrimaryTaskUpsertOne is the builder for "upsert"-ing
	//  one ImagePrimaryTask node.
	ImagePrimaryTaskUpsertOne struct {
		create *ImagePrimaryTaskCreate
	}

	// ImagePrimaryTaskUpsert is the "OnConflict" setter.
	ImagePrimaryTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ImagePrimaryTaskUpsert) SetUserID(v int64) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateUserID() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ImagePrimaryTaskUpsert) AddUserID(v int64) *ImagePrimaryTaskUpsert {
	u.Add(imageprimarytask.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImagePrimaryTaskUpsert) SetAPIKeyID(v int64) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateAPIKeyID() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImagePrimaryTaskUpsert) AddAPIKeyID(v int64) *ImagePrimaryTaskUpsert {
	u.Add(imageprimarytask.FieldAPIKeyID, v)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsert) SetUsageLogID(v int64) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateUsageLogID() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsert) AddUsageLogID(v int64) *ImagePrimaryTaskUpsert {
	u.Add(imageprimarytask.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsert) ClearUsageLogID() *ImagePrimaryTaskUpsert {
	u.SetNull(imageprimarytask.FieldUsageLogID)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *ImagePrimaryTaskUpsert) SetProtocol(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateProtocol() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldProtocol)
	return u
}

// SetModel sets the "model" field.
func (u *ImagePrimaryTaskUpsert) SetModel(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateModel() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldModel)
	return u
}

// SetRequestHash sets the "request_hash" field.
func (u *ImagePrimaryTaskUpsert) SetRequestHash(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldRequestHash, v)
	return u
}

// UpdateRequestHash sets the "request_hash" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateRequestHash() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldRequestHash)
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *ImagePrimaryTaskUpsert) SetUpstreamTaskID(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldUpstreamTaskID, v)
	return u
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateUpstreamTaskID() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldUpstreamTaskID)
	return u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *ImagePrimaryTaskUpsert) ClearUpstreamTaskID() *ImagePrimaryTaskUpsert {
	u.SetNull(imageprimarytask.FieldUpstreamTaskID)
	return u
}

// SetStatus sets the "status" field.
func (u *ImagePrimaryTaskUpsert) SetStatus(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateStatus() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldStatus)
	return u
}

// SetFallbackReason sets the "fallback_reason" field.
func (u *ImagePrimaryTaskUpsert) SetFallbackReason(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldFallbackReason, v)
	return u
}

// UpdateFallbackReason sets the "fallback_reason" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateFallbackReason() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldFallbackReason)
	return u
}

// ClearFallbackReason clears the value of the "fallback_reason" field.
func (u *ImagePrimaryTaskUpsert) ClearFallbackReason() *ImagePrimaryTaskUpsert {
	u.SetNull(imageprimarytask.FieldFallbackReason)
	return u
}

// SetResultLocator sets the "result_locator" field.
func (u *ImagePrimaryTaskUpsert) SetResultLocator(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldResultLocator, v)
	return u
}

// UpdateResultLocator sets the "result_locator" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateResultLocator() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldResultLocator)
	return u
}

// ClearResultLocator clears the value of the "result_locator" field.
func (u *ImagePrimaryTaskUpsert) ClearResultLocator() *ImagePrimaryTaskUpsert {
	u.SetNull(imageprimarytask.FieldResultLocator)
	return u
}

// SetImageCount sets the "image_count" field.
func (u *ImagePrimaryTaskUpsert) SetImageCount(v int) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldImageCount, v)
	return u
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateImageCount() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldImageCount)
	return u
}

// AddImageCount adds v to the "image_count" field.
func (u *ImagePrimaryTaskUpsert) AddImageCount(v int) *ImagePrimaryTaskUpsert {
	u.Add(imageprimarytask.FieldImageCount, v)
	return u
}

// SetImageSize sets the "image_size" field.
func (u *ImagePrimaryTaskUpsert) SetImageSize(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldImageSize, v)
	return u
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateImageSize() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldImageSize)
	return u
}

// ClearImageSize clears the value of the "image_size" field.
func (u *ImagePrimaryTaskUpsert) ClearImageSize() *ImagePrimaryTaskUpsert {
	u.SetNull(imageprimarytask.FieldImageSize)
	return u
}

// SetPrimaryDurationMs sets the "primary_duration_ms" field.
func (u *ImagePrimaryTaskUpsert) SetPrimaryDurationMs(v int64) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldPrimaryDurationMs, v)
	return u
}

// UpdatePrimaryDurationMs sets the "primary_duration_ms" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdatePrimaryDurationMs() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldPrimaryDurationMs)
	return u
}

// AddPrimaryDurationMs adds v to the "primary_duration_ms" field.
func (u *ImagePrimaryTaskUpsert) AddPrimaryDurationMs(v int64) *ImagePrimaryTaskUpsert {
	u.Add(imageprimarytask.FieldPrimaryDurationMs, v)
	return u
}

// SetFallbackDurationMs sets the "fallback_duration_ms" field.
func (u *ImagePrimaryTaskUpsert) SetFallbackDurationMs(v int64) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldFallbackDurationMs, v)
	return u
}

// UpdateFallbackDurationMs sets the "fallback_duration_ms" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateFallbackDurationMs() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldFallbackDurationMs)
	return u
}

// AddFallbackDurationMs adds v to the "fallback_duration_ms" field.
func (u *ImagePrimaryTaskUpsert) AddFallbackDurationMs(v int64) *ImagePrimaryTaskUpsert {
	u.Add(imageprimarytask.FieldFallbackDurationMs, v)
	return u
}

// SetSettlementState sets the "settlement_state" field.
func (u *ImagePrimaryTaskUpsert) SetSettlementState(v string) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldSettlementState, v)
	return u
}

// UpdateSettlementState sets the "settlement_state" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateSettlementState() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldSettlementState)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImagePrimaryTaskUpsert) SetUpdatedAt(v time.Time) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateUpdatedAt() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldUpdatedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ImagePrimaryTaskUpsert) SetExpiresAt(v time.Time) *ImagePrimaryTaskUpsert {
	u.Set(imageprimarytask.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsert) UpdateExpiresAt() *ImagePrimaryTaskUpsert {
	u.SetExcluded(imageprimarytask.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImagePrimaryTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImagePrimaryTaskUpsertOne) UpdateNewValues() *ImagePrimaryTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.PublicID(); exists {
			s.SetIgnore(imageprimarytask.FieldPublicID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imageprimarytask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImagePrimaryTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImagePrimaryTaskUpsertOne) Ignore() *ImagePrimaryTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImagePrimaryTaskUpsertOne) DoNothing() *ImagePrimaryTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImagePrimaryTaskCreate.OnConflict
// documentation for more info.
func (u *ImagePrimaryTaskUpsertOne) Update(set func(*ImagePrimaryTaskUpsert)) *ImagePrimaryTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImagePrimaryTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImagePrimaryTaskUpsertOne) SetUserID(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImagePrimaryTaskUpsertOne) AddUserID(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateUserID() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImagePrimaryTaskUpsertOne) SetAPIKeyID(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImagePrimaryTaskUpsertOne) AddAPIKeyID(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateAPIKeyID() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsertOne) SetUsageLogID(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsertOne) AddUsageLogID(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateUsageLogID() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsertOne) ClearUsageLogID() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearUsageLogID()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ImagePrimaryTaskUpsertOne) SetProtocol(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateProtocol() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateProtocol()
	})
}

// SetModel sets the "model" field.
func (u *ImagePrimaryTaskUpsertOne) SetModel(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateModel() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateModel()
	})
}

// SetRequestHash sets the "request_hash" field.
func (u *ImagePrimaryTaskUpsertOne) SetRequestHash(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetRequestHash(v)
	})
}

// UpdateRequestHash sets the "request_hash" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateRequestHash() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateRequestHash()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *ImagePrimaryTaskUpsertOne) SetUpstreamTaskID(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateUpstreamTaskID() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *ImagePrimaryTaskUpsertOne) ClearUpstreamTaskID() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetStatus sets the "status" field.
func (u *ImagePrimaryTaskUpsertOne) SetStatus(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateStatus() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetFallbackReason sets the "fallback_reason" field.
func (u *ImagePrimaryTaskUpsertOne) SetFallbackReason(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetFallbackReason(v)
	})
}

// UpdateFallbackReason sets the "fallback_reason" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateFallbackReason() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateFallbackReason()
	})
}

// ClearFallbackReason clears the value of the "fallback_reason" field.
func (u *ImagePrimaryTaskUpsertOne) ClearFallbackReason() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearFallbackReason()
	})
}

// SetResultLocator sets the "result_locator" field.
func (u *ImagePrimaryTaskUpsertOne) SetResultLocator(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetResultLocator(v)
	})
}

// UpdateResultLocator sets the "result_locator" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateResultLocator() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateResultLocator()
	})
}

// ClearResultLocator clears the value of the "result_locator" field.
func (u *ImagePrimaryTaskUpsertOne) ClearResultLocator() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearResultLocator()
	})
}

// SetImageCount sets the "image_count" field.
func (u *ImagePrimaryTaskUpsertOne) SetImageCount(v int) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *ImagePrimaryTaskUpsertOne) AddImageCount(v int) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateImageCount() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateImageCount()
	})
}

// SetImageSize sets the "image_size" field.
func (u *ImagePrimaryTaskUpsertOne) SetImageSize(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetImageSize(v)
	})
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateImageSize() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateImageSize()
	})
}

// ClearImageSize clears the value of the "image_size" field.
func (u *ImagePrimaryTaskUpsertOne) ClearImageSize() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearImageSize()
	})
}

// SetPrimaryDurationMs sets the "primary_duration_ms" field.
func (u *ImagePrimaryTaskUpsertOne) SetPrimaryDurationMs(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetPrimaryDurationMs(v)
	})
}

// AddPrimaryDurationMs adds v to the "primary_duration_ms" field.
func (u *ImagePrimaryTaskUpsertOne) AddPrimaryDurationMs(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddPrimaryDurationMs(v)
	})
}

// UpdatePrimaryDurationMs sets the "primary_duration_ms" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdatePrimaryDurationMs() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdatePrimaryDurationMs()
	})
}

// SetFallbackDurationMs sets the "fallback_duration_ms" field.
func (u *ImagePrimaryTaskUpsertOne) SetFallbackDurationMs(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetFallbackDurationMs(v)
	})
}

// AddFallbackDurationMs adds v to the "fallback_duration_ms" field.
func (u *ImagePrimaryTaskUpsertOne) AddFallbackDurationMs(v int64) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddFallbackDurationMs(v)
	})
}

// UpdateFallbackDurationMs sets the "fallback_duration_ms" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateFallbackDurationMs() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateFallbackDurationMs()
	})
}

// SetSettlementState sets the "settlement_state" field.
func (u *ImagePrimaryTaskUpsertOne) SetSettlementState(v string) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetSettlementState(v)
	})
}

// UpdateSettlementState sets the "settlement_state" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateSettlementState() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateSettlementState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImagePrimaryTaskUpsertOne) SetUpdatedAt(v time.Time) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateUpdatedAt() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ImagePrimaryTaskUpsertOne) SetExpiresAt(v time.Time) *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertOne) UpdateExpiresAt() *ImagePrimaryTaskUpsertOne {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *ImagePrimaryTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImagePrimaryTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImagePrimaryTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImagePrimaryTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImagePrimaryTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImagePrimaryTaskCreateBulk is the builder for creating many ImagePrimaryTask entities in bulk.
type ImagePrimaryTaskCreateBulk struct {
	config
	err      error
	builders []*ImagePrimaryTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the ImagePrimaryTask entities in the database.
func (_c *ImagePrimaryTaskCreateBulk) Save(ctx context.Context) ([]*ImagePrimaryTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImagePrimaryTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImagePrimaryTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImagePrimaryTaskCreateBulk) SaveX(ctx context.Context) []*ImagePrimaryTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImagePrimaryTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImagePrimaryTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImagePrimaryTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImagePrimaryTaskUpsert) {
//			SetPublicID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImagePrimaryTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImagePrimaryTaskUpsertBulk {
	_c.conflict = opts
	return &ImagePrimaryTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImagePrimaryTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImagePrimaryTaskCreateBulk) OnConflictColumns(columns ...string) *ImagePrimaryTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImagePrimaryTaskUpsertBulk{
		create: _c,
	}
}

// ImagePrimaryTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of ImagePrimaryTask nodes.
type ImagePrimaryTaskUpsertBulk struct {
	create *ImagePrimaryTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImagePrimaryTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImagePrimaryTaskUpsertBulk) UpdateNewValues() *ImagePrimaryTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.PublicID(); exists {
				s.SetIgnore(imageprimarytask.FieldPublicID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imageprimarytask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImagePrimaryTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImagePrimaryTaskUpsertBulk) Ignore() *ImagePrimaryTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImagePrimaryTaskUpsertBulk) DoNothing() *ImagePrimaryTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImagePrimaryTaskCreateBulk.OnConflict
// documentation for more info.
func (u *ImagePrimaryTaskUpsertBulk) Update(set func(*ImagePrimaryTaskUpsert)) *ImagePrimaryTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImagePrimaryTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImagePrimaryTaskUpsertBulk) SetUserID(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImagePrimaryTaskUpsertBulk) AddUserID(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateUserID() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImagePrimaryTaskUpsertBulk) SetAPIKeyID(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImagePrimaryTaskUpsertBulk) AddAPIKeyID(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateAPIKeyID() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsertBulk) SetUsageLogID(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsertBulk) AddUsageLogID(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateUsageLogID() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *ImagePrimaryTaskUpsertBulk) ClearUsageLogID() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearUsageLogID()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ImagePrimaryTaskUpsertBulk) SetProtocol(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateProtocol() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateProtocol()
	})
}

// SetModel sets the "model" field.
func (u *ImagePrimaryTaskUpsertBulk) SetModel(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateModel() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateModel()
	})
}

// SetRequestHash sets the "request_hash" field.
func (u *ImagePrimaryTaskUpsertBulk) SetRequestHash(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetRequestHash(v)
	})
}

// UpdateRequestHash sets the "request_hash" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateRequestHash() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateRequestHash()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *ImagePrimaryTaskUpsertBulk) SetUpstreamTaskID(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateUpstreamTaskID() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *ImagePrimaryTaskUpsertBulk) ClearUpstreamTaskID() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetStatus sets the "status" field.
func (u *ImagePrimaryTaskUpsertBulk) SetStatus(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateStatus() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetFallbackReason sets the "fallback_reason" field.
func (u *ImagePrimaryTaskUpsertBulk) SetFallbackReason(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetFallbackReason(v)
	})
}

// UpdateFallbackReason sets the "fallback_reason" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateFallbackReason() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateFallbackReason()
	})
}

// ClearFallbackReason clears the value of the "fallback_reason" field.
func (u *ImagePrimaryTaskUpsertBulk) ClearFallbackReason() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearFallbackReason()
	})
}

// SetResultLocator sets the "result_locator" field.
func (u *ImagePrimaryTaskUpsertBulk) SetResultLocator(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetResultLocator(v)
	})
}

// UpdateResultLocator sets the "result_locator" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateResultLocator() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateResultLocator()
	})
}

// ClearResultLocator clears the value of the "result_locator" field.
func (u *ImagePrimaryTaskUpsertBulk) ClearResultLocator() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearResultLocator()
	})
}

// SetImageCount sets the "image_count" field.
func (u *ImagePrimaryTaskUpsertBulk) SetImageCount(v int) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *ImagePrimaryTaskUpsertBulk) AddImageCount(v int) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateImageCount() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateImageCount()
	})
}

// SetImageSize sets the "image_size" field.
func (u *ImagePrimaryTaskUpsertBulk) SetImageSize(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetImageSize(v)
	})
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateImageSize() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateImageSize()
	})
}

// ClearImageSize clears the value of the "image_size" field.
func (u *ImagePrimaryTaskUpsertBulk) ClearImageSize() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.ClearImageSize()
	})
}

// SetPrimaryDurationMs sets the "primary_duration_ms" field.
func (u *ImagePrimaryTaskUpsertBulk) SetPrimaryDurationMs(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetPrimaryDurationMs(v)
	})
}

// AddPrimaryDurationMs adds v to the "primary_duration_ms" field.
func (u *ImagePrimaryTaskUpsertBulk) AddPrimaryDurationMs(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddPrimaryDurationMs(v)
	})
}

// UpdatePrimaryDurationMs sets the "primary_duration_ms" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdatePrimaryDurationMs() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdatePrimaryDurationMs()
	})
}

// SetFallbackDurationMs sets the "fallback_duration_ms" field.
func (u *ImagePrimaryTaskUpsertBulk) SetFallbackDurationMs(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetFallbackDurationMs(v)
	})
}

// AddFallbackDurationMs adds v to the "fallback_duration_ms" field.
func (u *ImagePrimaryTaskUpsertBulk) AddFallbackDurationMs(v int64) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.AddFallbackDurationMs(v)
	})
}

// UpdateFallbackDurationMs sets the "fallback_duration_ms" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateFallbackDurationMs() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateFallbackDurationMs()
	})
}

// SetSettlementState sets the "settlement_state" field.
func (u *ImagePrimaryTaskUpsertBulk) SetSettlementState(v string) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetSettlementState(v)
	})
}

// UpdateSettlementState sets the "settlement_state" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateSettlementState() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateSettlementState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImagePrimaryTaskUpsertBulk) SetUpdatedAt(v time.Time) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateUpdatedAt() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ImagePrimaryTaskUpsertBulk) SetExpiresAt(v time.Time) *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ImagePrimaryTaskUpsertBulk) UpdateExpiresAt() *ImagePrimaryTaskUpsertBulk {
	return u.Update(func(s *ImagePrimaryTaskUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *ImagePrimaryTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImagePrimaryTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImagePrimaryTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImagePrimaryTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
