// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imageprimarytask"
)

// ImagePrimaryTask is the model entity for the ImagePrimaryTask schema.
type ImagePrimaryTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// FallbackReason holds the value of the "fallback_reason" field.
	FallbackReason *string `json:"fallback_reason,omitempty"`
	// ResultLocator holds the value of the "result_locator" field.
	ResultLocator *string `json:"result_locator,omitempty"`
	// ImageCount holds the value of the "image_count" field.
	ImageCount int `json:"image_count,omitempty"`
	// ImageSize holds the value of the "image_size" field.
	ImageSize *string `json:"image_size,omitempty"`
	// PrimaryDurationMs holds the value of the "primary_duration_ms" field.
	PrimaryDurationMs int64 `json:"primary_duration_ms,omitempty"`
	// FallbackDurationMs holds the value of the "fallback_duration_ms" field.
	FallbackDurationMs int64 `json:"fallback_duration_ms,omitempty"`
	// SettlementState holds the value of the "settlement_state" field.
	SettlementState string `json:"settlement_state,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImagePrimaryTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imageprimarytask.FieldID, imageprimarytask.FieldUserID, imageprimarytask.FieldAPIKeyID, imageprimarytask.FieldUsageLogID, imageprimarytask.FieldImageCount, imageprimarytask.FieldPrimaryDurationMs, imageprimarytask.FieldFallbackDurationMs:
			values[i] = new(sql.NullInt64)
		case imageprimarytask.FieldPublicID, imageprimarytask.FieldProtocol, imageprimarytask.FieldModel, imageprimarytask.FieldRequestHash, imageprimarytask.FieldUpstreamTaskID, imageprimarytask.FieldStatus, imageprimarytask.FieldFallbackReason, imageprimarytask.FieldResultLocator, imageprimarytask.FieldImageSize, imageprimarytask.FieldSettlementState:
			values[i] = new(sql.NullString)
		case imageprimarytask.FieldCreatedAt, imageprimarytask.FieldUpdatedAt, imageprimarytask.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImagePrimaryTask fields.
func (_m *ImagePrimaryTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imageprimarytask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imageprimarytask.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case imageprimarytask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case imageprimarytask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case imageprimarytask.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case imageprimarytask.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case imageprimarytask.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case imageprimarytask.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case imageprimarytask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case imageprimarytask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imageprimarytask.FieldFallbackReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_reason", values[i])
			} else if value.Valid {
				_m.FallbackReason = new(string)
				*_m.FallbackReason = value.String
			}
		case imageprimarytask.FieldResultLocator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_locator", values[i])
			} else if value.Valid {
				_m.ResultLocator = new(string)
				*_m.ResultLocator = value.String
			}
		case imageprimarytask.FieldImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_count", values[i])
			} else if value.Valid {
				_m.ImageCount = int(value.Int64)
			}
		case imageprimarytask.FieldImageSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size", values[i])
			} else if value.Valid {
				_m.ImageSize = new(string)
				*_m.ImageSize = value.String
			}
		case imageprimarytask.FieldPrimaryDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field primary_duration_ms", values[i])
			} else if value.Valid {
				_m.PrimaryDurationMs = value.Int64
			}
		case imageprimarytask.FieldFallbackDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_duration_ms", values[i])
			} else if value.Valid {
				_m.FallbackDurationMs = value.Int64
			}
		case imageprimarytask.FieldSettlementState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_state", values[i])
			} else if value.Valid {
				_m.SettlementState = value.String
			}
		case imageprimarytask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imageprimarytask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imageprimarytask.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImagePrimaryTask.
// This includes values selected through modifiers, order, etc.
func (_m *ImagePrimaryTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImagePrimaryTask.
// Note that you need to call ImagePrimaryTask.Unwrap() before calling this method if this ImagePrimaryTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImagePrimaryTask) Update() *ImagePrimaryTaskUpdateOne {
	return NewImagePrimaryTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImagePrimaryTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImagePrimaryTask) Unwrap() *ImagePrimaryTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImagePrimaryTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImagePrimaryTask) String() string {
	var builder strings.Builder
	builder.WriteString("ImagePrimaryTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.FallbackReason; v != nil {
		builder.WriteString("fallback_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultLocator; v != nil {
		builder.WriteString("result_locator=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageCount))
	builder.WriteString(", ")
	if v := _m.ImageSize; v != nil {
		builder.WriteString("image_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("primary_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrimaryDurationMs))
	builder.WriteString(", ")
	builder.WriteString("fallback_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.FallbackDurationMs))
	builder.WriteString(", ")
	builder.WriteString("settlement_state=")
	builder.WriteString(_m.SettlementState)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImagePrimaryTasks is a parsable slice of ImagePrimaryTask.
type ImagePrimaryTasks []*ImagePrimaryTask
