// Code generated by ent, DO NOT EDIT.

package imageprimarytask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the imageprimarytask type in the database.
	Label = "image_primary_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFallbackReason holds the string denoting the fallback_reason field in the database.
	FieldFallbackReason = "fallback_reason"
	// FieldResultLocator holds the string denoting the result_locator field in the database.
	FieldResultLocator = "result_locator"
	// FieldImageCount holds the string denoting the image_count field in the database.
	FieldImageCount = "image_count"
	// FieldImageSize holds the string denoting the image_size field in the database.
	FieldImageSize = "image_size"
	// FieldPrimaryDurationMs holds the string denoting the primary_duration_ms field in the database.
	FieldPrimaryDurationMs = "primary_duration_ms"
	// FieldFallbackDurationMs holds the string denoting the fallback_duration_ms field in the database.
	FieldFallbackDurationMs = "fallback_duration_ms"
	// FieldSettlementState holds the string denoting the settlement_state field in the database.
	FieldSettlementState = "settlement_state"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the imageprimarytask in the database.
	Table = "image_primary_tasks"
)

// Columns holds all SQL columns for imageprimarytask fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldUserID,
	FieldAPIKeyID,
	FieldUsageLogID,
	FieldProtocol,
	FieldModel,
	FieldRequestHash,
	FieldUpstreamTaskID,
	FieldStatus,
	FieldFallbackReason,
	FieldResultLocator,
	FieldImageCount,
	FieldImageSize,
	FieldPrimaryDurationMs,
	FieldFallbackDurationMs,
	FieldSettlementState,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// FallbackReasonValidator is a validator for the "fallback_reason" field. It is called by the builders before save.
	FallbackReasonValidator func(string) error
	// DefaultImageCount holds the default value on creation for the "image_count" field.
	DefaultImageCount int
	// ImageSizeValidator is a validator for the "image_size" field. It is called by the builders before save.
	ImageSizeValidator func(string) error
	// DefaultPrimaryDurationMs holds the default value on creation for the "primary_duration_ms" field.
	DefaultPrimaryDurationMs int64
	// DefaultFallbackDurationMs holds the default value on creation for the "fallback_duration_ms" field.
	DefaultFallbackDurationMs int64
	// DefaultSettlementState holds the default value on creation for the "settlement_state" field.
	DefaultSettlementState string
	// SettlementStateValidator is a validator for the "settlement_state" field. It is called by the builders before save.
	SettlementStateValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ImagePrimaryTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFallbackReason orders the results by the fallback_reason field.
func ByFallbackReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFallbackReason, opts...).ToFunc()
}

// ByResultLocator orders the results by the result_locator field.
func ByResultLocator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultLocator, opts...).ToFunc()
}

// ByImageCount orders the results by the image_count field.
func ByImageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageCount, opts...).ToFunc()
}

// ByImageSize orders the results by the image_size field.
func ByImageSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageSize, opts...).ToFunc()
}

// ByPrimaryDurationMs orders the results by the primary_duration_ms field.
func ByPrimaryDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryDurationMs, opts...).ToFunc()
}

// ByFallbackDurationMs orders the results by the fallback_duration_ms field.
func ByFallbackDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFallbackDurationMs, opts...).ToFunc()
}

// BySettlementState orders the results by the settlement_state field.
func BySettlementState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementState, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
