// Code generated by ent, DO NOT EDIT.

package imageprimarytask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldPublicID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUsageLogID, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldProtocol, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldModel, v))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldRequestHash, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldStatus, v))
}

// FallbackReason applies equality check predicate on the "fallback_reason" field. It's identical to FallbackReasonEQ.
func FallbackReason(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldFallbackReason, v))
}

// ResultLocator applies equality check predicate on the "result_locator" field. It's identical to ResultLocatorEQ.
func ResultLocator(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldResultLocator, v))
}

// ImageCount applies equality check predicate on the "image_count" field. It's identical to ImageCountEQ.
func ImageCount(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldImageCount, v))
}

// ImageSize applies equality check predicate on the "image_size" field. It's identical to ImageSizeEQ.
func ImageSize(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldImageSize, v))
}

// PrimaryDurationMs applies equality check predicate on the "primary_duration_ms" field. It's identical to PrimaryDurationMsEQ.
func PrimaryDurationMs(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldPrimaryDurationMs, v))
}

// FallbackDurationMs applies equality check predicate on the "fallback_duration_ms" field. It's identical to FallbackDurationMsEQ.
func FallbackDurationMs(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldFallbackDurationMs, v))
}

// SettlementState applies equality check predicate on the "settlement_state" field. It's identical to SettlementStateEQ.
func SettlementState(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldSettlementState, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldExpiresAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldPublicID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldAPIKeyID, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotNull(FieldUsageLogID))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldProtocol, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldModel, v))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldRequestHash, v))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIsNil applies the IsNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDIsNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIsNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDNotNil applies the NotNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldStatus, v))
}

// FallbackReasonEQ applies the EQ predicate on the "fallback_reason" field.
func FallbackReasonEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldFallbackReason, v))
}

// FallbackReasonNEQ applies the NEQ predicate on the "fallback_reason" field.
func FallbackReasonNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldFallbackReason, v))
}

// FallbackReasonIn applies the In predicate on the "fallback_reason" field.
func FallbackReasonIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldFallbackReason, vs...))
}

// FallbackReasonNotIn applies the NotIn predicate on the "fallback_reason" field.
func FallbackReasonNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldFallbackReason, vs...))
}

// FallbackReasonGT applies the GT predicate on the "fallback_reason" field.
func FallbackReasonGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldFallbackReason, v))
}

// FallbackReasonGTE applies the GTE predicate on the "fallback_reason" field.
func FallbackReasonGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldFallbackReason, v))
}

// FallbackReasonLT applies the LT predicate on the "fallback_reason" field.
func FallbackReasonLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldFallbackReason, v))
}

// FallbackReasonLTE applies the LTE predicate on the "fallback_reason" field.
func FallbackReasonLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldFallbackReason, v))
}

// FallbackReasonContains applies the Contains predicate on the "fallback_reason" field.
func FallbackReasonContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldFallbackReason, v))
}

// FallbackReasonHasPrefix applies the HasPrefix predicate on the "fallback_reason" field.
func FallbackReasonHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldFallbackReason, v))
}

// FallbackReasonHasSuffix applies the HasSuffix predicate on the "fallback_reason" field.
func FallbackReasonHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldFallbackReason, v))
}

// FallbackReasonIsNil applies the IsNil predicate on the "fallback_reason" field.
func FallbackReasonIsNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIsNull(FieldFallbackReason))
}

// FallbackReasonNotNil applies the NotNil predicate on the "fallback_reason" field.
func FallbackReasonNotNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotNull(FieldFallbackReason))
}

// FallbackReasonEqualFold applies the EqualFold predicate on the "fallback_reason" field.
func FallbackReasonEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldFallbackReason, v))
}

// FallbackReasonContainsFold applies the ContainsFold predicate on the "fallback_reason" field.
func FallbackReasonContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldFallbackReason, v))
}

// ResultLocatorEQ applies the EQ predicate on the "result_locator" field.
func ResultLocatorEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldResultLocator, v))
}

// ResultLocatorNEQ applies the NEQ predicate on the "result_locator" field.
func ResultLocatorNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldResultLocator, v))
}

// ResultLocatorIn applies the In predicate on the "result_locator" field.
func ResultLocatorIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldResultLocator, vs...))
}

// ResultLocatorNotIn applies the NotIn predicate on the "result_locator" field.
func ResultLocatorNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldResultLocator, vs...))
}

// ResultLocatorGT applies the GT predicate on the "result_locator" field.
func ResultLocatorGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldResultLocator, v))
}

// ResultLocatorGTE applies the GTE predicate on the "result_locator" field.
func ResultLocatorGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldResultLocator, v))
}

// ResultLocatorLT applies the LT predicate on the "result_locator" field.
func ResultLocatorLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldResultLocator, v))
}

// ResultLocatorLTE applies the LTE predicate on the "result_locator" field.
func ResultLocatorLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldResultLocator, v))
}

// ResultLocatorContains applies the Contains predicate on the "result_locator" field.
func ResultLocatorContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldResultLocator, v))
}

// ResultLocatorHasPrefix applies the HasPrefix predicate on the "result_locator" field.
func ResultLocatorHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldResultLocator, v))
}

// ResultLocatorHasSuffix applies the HasSuffix predicate on the "result_locator" field.
func ResultLocatorHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldResultLocator, v))
}

// ResultLocatorIsNil applies the IsNil predicate on the "result_locator" field.
func ResultLocatorIsNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIsNull(FieldResultLocator))
}

// ResultLocatorNotNil applies the NotNil predicate on the "result_locator" field.
func ResultLocatorNotNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotNull(FieldResultLocator))
}

// ResultLocatorEqualFold applies the EqualFold predicate on the "result_locator" field.
func ResultLocatorEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldResultLocator, v))
}

// ResultLocatorContainsFold applies the ContainsFold predicate on the "result_locator" field.
func ResultLocatorContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldResultLocator, v))
}

// ImageCountEQ applies the EQ predicate on the "image_count" field.
func ImageCountEQ(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldImageCount, v))
}

// ImageCountNEQ applies the NEQ predicate on the "image_count" field.
func ImageCountNEQ(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldImageCount, v))
}

// ImageCountIn applies the In predicate on the "image_count" field.
func ImageCountIn(vs ...int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldImageCount, vs...))
}

// ImageCountNotIn applies the NotIn predicate on the "image_count" field.
func ImageCountNotIn(vs ...int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldImageCount, vs...))
}

// ImageCountGT applies the GT predicate on the "image_count" field.
func ImageCountGT(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldImageCount, v))
}

// ImageCountGTE applies the GTE predicate on the "image_count" field.
func ImageCountGTE(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldImageCount, v))
}

// ImageCountLT applies the LT predicate on the "image_count" field.
func ImageCountLT(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldImageCount, v))
}

// ImageCountLTE applies the LTE predicate on the "image_count" field.
func ImageCountLTE(v int) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldImageCount, v))
}

// ImageSizeEQ applies the EQ predicate on the "image_size" field.
func ImageSizeEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldImageSize, v))
}

// ImageSizeNEQ applies the NEQ predicate on the "image_size" field.
func ImageSizeNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldImageSize, v))
}

// ImageSizeIn applies the In predicate on the "image_size" field.
func ImageSizeIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldImageSize, vs...))
}

// ImageSizeNotIn applies the NotIn predicate on the "image_size" field.
func ImageSizeNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldImageSize, vs...))
}

// ImageSizeGT applies the GT predicate on the "image_size" field.
func ImageSizeGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldImageSize, v))
}

// ImageSizeGTE applies the GTE predicate on the "image_size" field.
func ImageSizeGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldImageSize, v))
}

// ImageSizeLT applies the LT predicate on the "image_size" field.
func ImageSizeLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldImageSize, v))
}

// ImageSizeLTE applies the LTE predicate on the "image_size" field.
func ImageSizeLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldImageSize, v))
}

// ImageSizeContains applies the Contains predicate on the "image_size" field.
func ImageSizeContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldImageSize, v))
}

// ImageSizeHasPrefix applies the HasPrefix predicate on the "image_size" field.
func ImageSizeHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldImageSize, v))
}

// ImageSizeHasSuffix applies the HasSuffix predicate on the "image_size" field.
func ImageSizeHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldImageSize, v))
}

// ImageSizeIsNil applies the IsNil predicate on the "image_size" field.
func ImageSizeIsNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIsNull(FieldImageSize))
}

// ImageSizeNotNil applies the NotNil predicate on the "image_size" field.
func ImageSizeNotNil() predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotNull(FieldImageSize))
}

// ImageSizeEqualFold applies the EqualFold predicate on the "image_size" field.
func ImageSizeEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldImageSize, v))
}

// ImageSizeContainsFold applies the ContainsFold predicate on the "image_size" field.
func ImageSizeContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldImageSize, v))
}

// PrimaryDurationMsEQ applies the EQ predicate on the "primary_duration_ms" field.
func PrimaryDurationMsEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldPrimaryDurationMs, v))
}

// PrimaryDurationMsNEQ applies the NEQ predicate on the "primary_duration_ms" field.
func PrimaryDurationMsNEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldPrimaryDurationMs, v))
}

// PrimaryDurationMsIn applies the In predicate on the "primary_duration_ms" field.
func PrimaryDurationMsIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldPrimaryDurationMs, vs...))
}

// PrimaryDurationMsNotIn applies the NotIn predicate on the "primary_duration_ms" field.
func PrimaryDurationMsNotIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldPrimaryDurationMs, vs...))
}

// PrimaryDurationMsGT applies the GT predicate on the "primary_duration_ms" field.
func PrimaryDurationMsGT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldPrimaryDurationMs, v))
}

// PrimaryDurationMsGTE applies the GTE predicate on the "primary_duration_ms" field.
func PrimaryDurationMsGTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldPrimaryDurationMs, v))
}

// PrimaryDurationMsLT applies the LT predicate on the "primary_duration_ms" field.
func PrimaryDurationMsLT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldPrimaryDurationMs, v))
}

// PrimaryDurationMsLTE applies the LTE predicate on the "primary_duration_ms" field.
func PrimaryDurationMsLTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldPrimaryDurationMs, v))
}

// FallbackDurationMsEQ applies the EQ predicate on the "fallback_duration_ms" field.
func FallbackDurationMsEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldFallbackDurationMs, v))
}

// FallbackDurationMsNEQ applies the NEQ predicate on the "fallback_duration_ms" field.
func FallbackDurationMsNEQ(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldFallbackDurationMs, v))
}

// FallbackDurationMsIn applies the In predicate on the "fallback_duration_ms" field.
func FallbackDurationMsIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldFallbackDurationMs, vs...))
}

// FallbackDurationMsNotIn applies the NotIn predicate on the "fallback_duration_ms" field.
func FallbackDurationMsNotIn(vs ...int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldFallbackDurationMs, vs...))
}

// FallbackDurationMsGT applies the GT predicate on the "fallback_duration_ms" field.
func FallbackDurationMsGT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldFallbackDurationMs, v))
}

// FallbackDurationMsGTE applies the GTE predicate on the "fallback_duration_ms" field.
func FallbackDurationMsGTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldFallbackDurationMs, v))
}

// FallbackDurationMsLT applies the LT predicate on the "fallback_duration_ms" field.
func FallbackDurationMsLT(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldFallbackDurationMs, v))
}

// FallbackDurationMsLTE applies the LTE predicate on the "fallback_duration_ms" field.
func FallbackDurationMsLTE(v int64) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldFallbackDurationMs, v))
}

// SettlementStateEQ applies the EQ predicate on the "settlement_state" field.
func SettlementStateEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldSettlementState, v))
}

// SettlementStateNEQ applies the NEQ predicate on the "settlement_state" field.
func SettlementStateNEQ(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldSettlementState, v))
}

// SettlementStateIn applies the In predicate on the "settlement_state" field.
func SettlementStateIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldSettlementState, vs...))
}

// SettlementStateNotIn applies the NotIn predicate on the "settlement_state" field.
func SettlementStateNotIn(vs ...string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldSettlementState, vs...))
}

// SettlementStateGT applies the GT predicate on the "settlement_state" field.
func SettlementStateGT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldSettlementState, v))
}

// SettlementStateGTE applies the GTE predicate on the "settlement_state" field.
func SettlementStateGTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldSettlementState, v))
}

// SettlementStateLT applies the LT predicate on the "settlement_state" field.
func SettlementStateLT(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldSettlementState, v))
}

// SettlementStateLTE applies the LTE predicate on the "settlement_state" field.
func SettlementStateLTE(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldSettlementState, v))
}

// SettlementStateContains applies the Contains predicate on the "settlement_state" field.
func SettlementStateContains(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContains(FieldSettlementState, v))
}

// SettlementStateHasPrefix applies the HasPrefix predicate on the "settlement_state" field.
func SettlementStateHasPrefix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasPrefix(FieldSettlementState, v))
}

// SettlementStateHasSuffix applies the HasSuffix predicate on the "settlement_state" field.
func SettlementStateHasSuffix(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldHasSuffix(FieldSettlementState, v))
}

// SettlementStateEqualFold applies the EqualFold predicate on the "settlement_state" field.
func SettlementStateEqualFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEqualFold(FieldSettlementState, v))
}

// SettlementStateContainsFold applies the ContainsFold predicate on the "settlement_state" field.
func SettlementStateContainsFold(v string) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldContainsFold(FieldSettlementState, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImagePrimaryTask) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImagePrimaryTask) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImagePrimaryTask) predicate.ImagePrimaryTask {
	return predicate.ImagePrimaryTask(sql.NotPredicates(p))
}
